# LogDataset

A brief overview over the dataset created.

In [30]:
from pylon_experiments.data.log_dataset import LogDataset

train_ds = LogDataset.load("../data/bpic2012/datasets/train.pkl")
print(f"Number of traces: {len(train_ds)}", end="\n\n")
for i in range(3):
    print(f"Trace {i}: {train_ds.traces_lengths[i]} events")
    print(train_ds.traces[i], end="\n\n")

Number of traces: 152612

Trace 0: 32 events
[ 2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 16 17 16 17 16 17 16 17 16
 17 16 17 16 36 26 17  3]

Trace 1: 36 events
[ 2  4  5  6  7  8 15  8 15  8 15  8 15  8  9 10 11 12 13 14 15 16 17 16
 17 16 17 16 18 19 17 20 28 29 25  3]

Trace 2: 27 events
[ 2  4  5 33 34 35 34  6  7 35  8  9 11 10 12 13 14 15 16 17 16 17 16 26
 36 17  3]



In [31]:
for i in range(6):
    prefix, target, length = train_ds[i]
    print(f"Prefix {i}: {length} events")
    print(f"{prefix.numpy()} -> {target.numpy()}", end="\n\n")

Prefix 0: 1 events
[2] -> 4

Prefix 1: 2 events
[2 4] -> 5

Prefix 2: 3 events
[2 4 5] -> 6

Prefix 3: 4 events
[2 4 5 6] -> 7

Prefix 4: 5 events
[2 4 5 6 7] -> 8

Prefix 5: 6 events
[2 4 5 6 7 8] -> 9



In [32]:
for i in range(31, 37):
    prefix, target, length = train_ds[i]
    print(f"Prefix {i}: {length} events")
    print(f"{prefix.numpy()} -> {target.numpy()}", end="\n\n")

Prefix 31: 1 events
[2] -> 4

Prefix 32: 2 events
[2 4] -> 5

Prefix 33: 3 events
[2 4 5] -> 6

Prefix 34: 4 events
[2 4 5 6] -> 7

Prefix 35: 5 events
[2 4 5 6 7] -> 8

Prefix 36: 6 events
[2 4 5 6 7 8] -> 15



In [35]:
LogDataset.collate_fn([train_ds[0], train_ds[1]])

(tensor([[2, 4],
         [2, 0]]),
 tensor([5, 4]),
 tensor([2, 1]))